### ISSUE TITLE
A RAPID model that does not contain any interface definitions imports fine but results in nothing

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/RapidML-ReadyAPI-Plugin#8]
Reported by @daffinm in ZEN-1960.
A RAPID model that does not contain any interface definitions imports fine but results in nothing. Would be better if it gave some kind of warning, e.g. "The selected RAPID model does not contain any interface definitions!"

**Comment by daffinm** [comment]
@tfesenko "The selected RAPID-ML model does not contain any interface definitions!" Perfect! Done. Thanks.
