### ISSUE TITLE
RepreZen import should work with *.rapid files

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/RapidML-ReadyAPI-Plugin#9]
RepreZen import: only files with *.zen extension are supported.
Importing *,rapid files fails with a following message:

```
java.lang.RuntimeException: Cannot create a resource for 'file:/Users/<...>/TaxBlaster/models/TaxBlaster.rapid'; a registered resource factory is needed
```

Also make sure that default file extension for exported models (models created by "Export RepreZen" in SOAP UI) have a *.rapid extension by default.

**Comment by tfesenko** [comment]
@tedepstein , can you please review?

**Comment by daffinm** [comment]
@tfesenko Just tested this. .rapid files import fine and model exported from ReadyAPI has .rapid extension. So looks good to me.
